### ISSUE TITLE
Failed test after newest commit

### ISSUE THREAD

**Issue by ActuallyBreizhDev** [PhilipGeier/VNScript#21]
```
[xUnit.net 00:00:00.79]       Assert.Equal() Failure: Strings differ
[xUnit.net 00:00:00.79]                                         ↓ (pos 70)
[xUnit.net 00:00:00.79]       Expected: ···"d <IdentifierToken>.\nUnexpected token: <E"···
[xUnit.net 00:00:00.79]       Actual:   ···"d <IdentifierToken>.\r\nUnexpected token: <"···
[xUnit.net 00:00:00.79]                                         ↑ (pos 70)
[xUnit.net 00:00:00.79]       Stack Trace:
[xUnit.net 00:00:00.79]         /home/runner/work/VNScript/VNScript/VNScript.Tests/CodeAnalysis/EvaluationTests.cs(251,0): at VNScript.Tests.CodeAnalysis.EvaluationTests.AssertDiagnostics(String text, String expectedDiagnostics)
[xUnit.net 00:00:00.79]         /home/runner/work/VNScript/VNScript/VNScript.Tests/CodeAnalysis/EvaluationTests.cs(154,0): at VNScript.Tests.CodeAnalysis.EvaluationTests.Evaluator_BlockStatement_NoInfiniteLoop()
[xUnit.net 00:00:00.79]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[xUnit.net 00:00:00.79]            at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Should be in the EvaluationTest

**Comment by ActuallyBreizhDev** [comment]
Was fixed with the latest commit
